import { FormFieldOption } from './formTemplates';

export const sharedOptions: Record<string, FormFieldOption[]> = {
  gender: [
    { label: 'Male', value: 'male' },
    { label: 'Female', value: 'female' },
    { label: 'Non-binary', value: 'non-binary' },
    { label: 'Prefer to self-describe', value: 'self-describe' },
    { label: 'Prefer not to answer', value: 'prefer-not' },
  ],
  placementType: [
    { label: 'Foster Home', value: 'foster-home' },
    { label: 'Kinship Care', value: 'kinship-care' },
    { label: 'Group Home', value: 'group-home' },
    { label: 'Relative Care', value: 'relative-care' },
  ],
  race: [
    { label: 'White', value: 'white' },
    { label: 'Black or African American', value: 'black' },
    { label: 'American Indian or Alaska Native', value: 'native-american' },
    { label: 'Asian', value: 'asian' },
    { label: 'Native Hawaiian or Pacific Islander', value: 'pacific-islander' },
    { label: 'Two or more races', value: 'multiracial' },
    { label: 'Unknown', value: 'unknown' },
  ],
  ethnicity: [
    { label: 'Hispanic or Latino', value: 'hispanic' },
    { label: 'Not Hispanic or Latino', value: 'non-hispanic' },
    { label: 'Unknown', value: 'unknown' },
  ],
  maritalStatus: [
    { label: 'Single', value: 'single' },
    { label: 'Married', value: 'married' },
    { label: 'Divorced', value: 'divorced' },
    { label: 'Separated', value: 'separated' },
    { label: 'Widowed', value: 'widowed' },
    { label: 'Domestic Partnership', value: 'domestic-partnership' },
    { label: 'Prefer not to answer', value: 'prefer-not-to-answer' },
  ],
  relationshipToChild: [
    { label: 'Parent', value: 'parent' },
    { label: 'Stepparent', value: 'stepparent' },
    { label: 'Grandparent', value: 'grandparent' },
    { label: 'Sibling', value: 'sibling' },
    { label: 'Aunt/Uncle', value: 'aunt-uncle' },
    { label: 'Legal Guardian', value: 'legal-guardian' },
    { label: 'Foster Parent', value: 'foster-parent' },
    { label: 'Other', value: 'other' },
  ],
  yesNo: [
    { label: 'Yes', value: 'yes' },
    { label: 'No', value: 'no' },
  ],
  state: [
    { label: 'Alabama', value: 'AL' },
    { label: 'Alaska', value: 'AK' },
    { label: 'Arizona', value: 'AZ' },
    { label: 'Arkansas', value: 'AR' },
    { label: 'California', value: 'CA' },
    { label: 'Colorado', value: 'CO' },
    { label: 'Connecticut', value: 'CT' },
    { label: 'Delaware', value: 'DE' },
    { label: 'Florida', value: 'FL' },
    { label: 'Georgia', value: 'GA' },
    { label: 'Hawaii', value: 'HI' },
    { label: 'Idaho', value: 'ID' },
    { label: 'Illinois', value: 'IL' },
    { label: 'Indiana', value: 'IN' },
    { label: 'Iowa', value: 'IA' },
    { label: 'Kansas', value: 'KS' },
    { label: 'Kentucky', value: 'KY' },
    { label: 'Louisiana', value: 'LA' },
    { label: 'Maine', value: 'ME' },
    { label: 'Maryland', value: 'MD' },
    { label: 'Massachusetts', value: 'MA' },
    { label: 'Michigan', value: 'MI' },
    { label: 'Minnesota', value: 'MN' },
    { label: 'Mississippi', value: 'MS' },
    { label: 'Missouri', value: 'MO' },
    { label: 'Montana', value: 'MT' },
    { label: 'Nebraska', value: 'NE' },
    { label: 'Nevada', value: 'NV' },
    { label: 'New Hampshire', value: 'NH' },
    { label: 'New Jersey', value: 'NJ' },
    { label: 'New Mexico', value: 'NM' },
    { label: 'New York', value: 'NY' },
    { label: 'North Carolina', value: 'NC' },
    { label: 'North Dakota', value: 'ND' },
    { label: 'Ohio', value: 'OH' },
    { label: 'Oklahoma', value: 'OK' },
    { label: 'Oregon', value: 'OR' },
    { label: 'Pennsylvania', value: 'PA' },
    { label: 'Rhode Island', value: 'RI' },
    { label: 'South Carolina', value: 'SC' },
    { label: 'South Dakota', value: 'SD' },
    { label: 'Tennessee', value: 'TN' },
    { label: 'Texas', value: 'TX' },
    { label: 'Utah', value: 'UT' },
    { label: 'Vermont', value: 'VT' },
    { label: 'Virginia', value: 'VA' },
    { label: 'Washington', value: 'WA' },
    { label: 'West Virginia', value: 'WV' },
    { label: 'Wisconsin', value: 'WI' },
    { label: 'Wyoming', value: 'WY' },
  ],
  addressType: [
    { label: 'At home', value: 'home' },
    { label: 'Licensed Foster Home', value: 'fosterHome' },
    { label: 'Group Home', value: 'groupHome' },
    { label: 'Relative Care', value: 'relativeCare' },
    { label: 'Other', value: 'other' },
  ],
  language: [
    { label: 'English', value: 'english' },
    { label: 'Spanish', value: 'spanish' },
    { label: 'French', value: 'french' },
    { label: 'German', value: 'german' },
    { label: 'Chinese', value: 'chinese' },
    { label: 'Japanese', value: 'japanese' },
    { label: 'Korean', value: 'korean' },
    { label: 'Other', value: 'other' },
  ],
    serviceType: [
    { label: 'Therapy', value: 'therapy' },
    { label: 'Education', value: 'education' },
    { label: 'Healthcare', value: 'healthcare' },
    { label: 'Legal', value: 'legal' },
    { label: 'Case Management', value: 'case-management' },
    { label: 'Other', value: 'other' },
    ]
};

export function getOptions(key: string): FormFieldOption[] {
  return sharedOptions[key] ?? [];
}
